### ISSUE TITLE
Need clarification in the installation documentation

### ISSUE THREAD

**Issue by pierrepo** [thomasdenecker/bPeaks-application#30]
The installation procedure does not tell where exactly to download zip files: 

> Download the zip file

Maybe a link to this zip file could be useful: 

https://github.com/thomasdenecker/bPeaks-application/archive/master.zip

In addition, it is not clear if the entire repo is required. Could only `INSTALLATION_MAC_LINUX.sh` and `INSTALLATION_WINDOWS.bat` be sufficient an avoid downloading the 283 Mb of the repo?

**Comment by thomasdenecker** [comment]
Thank you for that remark. I will add the link in the README.

Yes, you have to download the entire repo. All the files necessary to use the application are in the repo. The 2 installation files are not enough.
